[window]
decorations = "None"
padding = { x = 2, y = 2 }
dynamic_padding = true

[font]
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }
normal = { family = "JetBrains Mono", style = "Medium" }
size = 12

[colors.primary]
foreground = "#ebdbb2"
background = "#282828"

[colors.normal]
black   = "#000000"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#83a598"
white   = "#ebdbb2"

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Block"
blinking = "On"
